image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  POSTGRES_PORT: "5432"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "1337"
  POSTGRES_DATABASE: "avito"

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose build
  artifacts:
    paths:
      - Dockerfile
      - docker-compose.yml

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - main